-- Create Users Table
create table if not exists users (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text unique not null,
  password text not null, 
  balance float8 default 10000.0,
  upi_id text unique,
  is_verified boolean default false,
  verification_code text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Transactions Table
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id), -- Optional link if we want strictly relational
  amount float8 not null,
  upi_id text not null,
  status text,
  latitude float8,
  longitude float8,
  device_id text,
  ip_address text,
  is_fraud boolean default false,
  message text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: RLS (Row Level Security) is enabled by default on new Supabase tables.
-- You might need to disable RLS or add policies for the 'anon' key to read/write.
-- For this demo, strictly for testing, you can run:
alter table users enable row level security;
create policy "Public Access" on users for all using (true);

alter table transactions enable row level security;
create policy "Public Access" on transactions for all using (true);
